name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install GitHub CLI
      run: sudo apt install -y gh

    - name: Authenticate GitHub CLI
      run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

    - name: Read release notes
      id: read_release_notes
      run: |
        RELEASE_NOTES=$(cat RELEASE.md)
        echo "::set-output name=notes::$RELEASE_NOTES"

    - name: Extract tag
      id: extract_tag
      run: |
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          TAG_NAME=${{ github.ref#refs/tags/ }}
          echo "::set-output name=tag::$TAG_NAME"
        else
          echo "This is not a tag."
        fi

    - name: Create GitHub Release
      run: |
        gh release create ${{ steps.extract_tag.outputs.tag }} --title ${{ steps.extract_tag.outputs.tag }} --notes "${{ steps.read_release_notes.outputs.notes }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

