name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install GitHub CLI
      run: sudo apt install -y gh

    - name: Authenticate GitHub CLI
      run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

    - name: Read release notes
      id: read_release_notes
      run: |
        RELEASE_NOTES=$(cat RELEASE.md)
        echo "notes=$RELEASE_NOTES" >> $GITHUB_ENV

    - name: Create GitHub Release
      run: |
        gh release create "${GITHUB_REF##*/}" --title "${GITHUB_REF##*/}" --notes "${notes}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

