name: Generate docs

on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  build-sources:
    name: Generate docs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - run: date +%F > todays-date
      - name: Install Neovim
        run: |
          sudo snap install nvim --classic
          nvim --version

      - name: Generating docs
        run: |
          nvim -l scripts/gen_vimdoc.lua

      - name: Commit and push documentation
        uses: ./.github/actions/commit-and-push
        with:
          commit-message: 'Update help doc'
          files: 'doc/*'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update README
        run: |
          nvim -l scripts/update_readme.lua

      - name: Commit and push README
        uses: ./.github/actions/commit-and-push
        with:
          commit-message: 'Update README based on pkg.json'
          files: 'README.md README.*.md'
          github_token: ${{ secrets.GITHUB_TOKEN }}
