name: Generate docs from Lua source

on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  build-sources:
    name: Generate docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Neovim
        run: |
          sudo snap install nvim --classic
          nvim --version

      - name: Generating docs
        run: |
          make gendoc 

      - name: Commit and push documentation
        uses: ./.github/actions/commit-and-push
        with:
          commit-message: 'Update Vimdoc based on Lua source'
          files: 'doc/*'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update README
        run: |
          make update_readme

      - name: Commit and push README
        uses: ./.github/actions/commit-and-push
        with:
          commit-message: 'Update README based on pkg.json'
          files: 'README.md README.*.md'
          github_token: ${{ secrets.GITHUB_TOKEN }}


