name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for your issue! We appreciate your feedback and will look into it as soon as possible. Please make sure to include all necessary details to help us assist you better."
        pr-message: "Thank you for your pull request! We appreciate your contribution. Please ensure that your changes are well documented and tested."
